openapi: 3.0.3
info:
  title: Straight Lines Creative Design Platform APIs
  description: |-
    This is a subset of the APIs available for the Straight Lines Creative Design Platform based on the OpenAPI 3.0 specification.  
    
    Some useful links:
    - [Straight Lines Web Site](https://www.str8lines.com)
    - [Example Integrations](https://github.com/str8lines/ai-integration-examples)
  contact:
    email: support@str8lines.com
  version: 1.0.0
servers:
  - url: https://ai-staging.str8lines.com/
tags:
  - name: image
    description: Everything related to the images. 
paths:
  /image/{imageId}:
    parameters:
      - name: imageId
        in: path
        description: ID of image to return
        required: true
        schema:
          type: integer
          format: int64
    patch:
      tags:
        - image
      summary: Update an existing image
      description: Update an existing image by Id
      operationId: updateImage
      requestBody:
        description: Update an image
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Image'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '400':
          description: Invalid ID supplied
        '401':
          description: Not authorized
    get:
      tags:
        - image
      summary: Retrieve a specific image by id
      description: Get the single image
      operationId: findImageById
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
        '400':
          description: Invalid id
  /image:
    get:
      tags:
        - image
      summary: Find images by specified criteria
      description: An image may be the 'parent' that contains many scenarios, or it may be a 'child' where it resides within a scenario of a parent image.  For parent only queries, include the 'is_option eq False' criteria
      operationId: findImages
      parameters:
        - name: filter_param
          in: query
          description: Limit the returned results using specified criteria
          required: false
          schema:
            type: string
        - name: children_limit
          in: query
          description: Limit the URLs generated for children images for better performance
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
        '400':
          description: Invalid status value
  
components:
  schemas:
    Image:
      type: object
      properties:
        _id:
          type: string
        file_name_os:
          type: string
          example: 123.png
        code:
          type: string
          example: 10023223
        shipDate:
          type: string
        is_option:
          type: boolean
        send_to_closet:
          type: string
          example: Yes
        closet_status:
          type: string